version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      #runas: root
    - location: scripts/start_server
      timeout: 300
      runas: codedeploy
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: codedeploy


version: 0.0
os: linux
files:
    - source: /index.html
      destination: /var/www/html/
hooks:
    BeforeInstall:
     - location: deploy/before_install
       timeout: 300
       runas: ubuntu  AfterInstall:    - location: deploy/restart_server      timeout: 300      runas: ubuntu
